window.functions = {
    burger: require('./modules/burger'),
    header_shadow: require('./modules/header-shadow'),
    modal: require('./modules/modal'),
    search: require('./modules/search'),
    filter: require('./modules/filter'),
    ovh: require('./modules/ovh'),
    scroll_top: require('./modules/scroll-top'),
    text_box: require('./modules/text-box'),
    dropdown: require('./modules/dropdown'),
    markers: require('./modules/markers'),
    expander: require('./modules/expander'),
    listing_views: require('./modules/listing-views'),
    sticky_sidebar: require('./modules/sticky-sidebar'),
    sticky_cta: require('./modules/sticky-cta'),
    sticky_message: require('./modules/sticky-message'),
    contenteditable: require('./modules/contenteditable'),
    hasheditable: require('./modules/hasheditable'),
    gallery_carousel: require('./modules/gallery-carousel'),
    listing_carousel: require('./modules/listing-carousel'),
    articles_carousel: require('./modules/articles-carousel'),
    home_bg: require('./modules/home-bg'),
    validation: require('./modules/validation'),
    shifting_text: require('./modules/shifting-text'),
    input_number: require('./modules/input-number'),
    init: require('./modules/init'),
};
