window.functions = {
    ovh: require('./modules/ovh'),
    burger: require('./modules/burger'),
    auth: require('./modules/auth'),
    scroll_top: require('./modules/scroll-top'),
    expander: require('./modules/expander'),
    table_expander: require('./modules/table-expander'),
    no_ui_slider: require('./modules/no-ui-slider'),
    gallery: require('./modules/gallery'),
    spinner: require('./modules/spinner'),
    validation: require('./modules/validation'),
    sticky_sidebar: require('./modules/sticky-sidebar'),
    carousel: require('./modules/carousel'),
    filled_input: require('./modules/filled-input'),
    textbox: require('./modules/textbox'),
    popup: require('./modules/popup'),
    orders_table: require('./modules/orders-table'),
    alert: require('./modules/alert'),
    parallax: require('./modules/parallax'),
    search: require('./modules/search'),
    filter_selector: require('./modules/filter-selector'),
    fn: require('./modules/fn'),
};

